server:
  port: 8016
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/api_open_platform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&rewriteBatchedStatements=true&allowMultiQueries=true&allowMultiQueries=true
    username: root
    password: 20030322
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    default-executor-type: batch
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
message-queue-meta:
  topic: API_SPACE_LOG
  common-log-tag: commonlog
  error-log-tag: errorlog
  proxy-server: 192.168.146.132:8081 # 服务代理访问地址
cryptographic:
  AESKey: hello
logging:
  level:
    root: info
#  file:
#    name: space.log